

// import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/navbar";




// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body >
        <Navbar />
          {children}
      </body>
    </html>
  );
}
